### PR TITLE
Unbind behavior

### PR DESCRIPTION
**Pull request by martinbrylski**
This alters the unbind behavior to better match expectations.

See #71

### CODE REVIEW

**Comment by scotttrinh** [comment]
Do you mind removing the version bumping parts of this PR? We will figure out what version this will go in as a separate commit, so no need to bump it here.

Also, the comment block above the unbind method describes the method as doing what it used to do. Since this is a breaking change, I'd rather have some discussion around this before needing to bump to 2.0.0 over this.

**Comment by scotttrinh** [comment]
@martinbrylski I'm going to make this change conditional on a second argument so we can keep backwards compatibility and get it in `1.3.0` instead of having to wait until a major version bump. Any thoughts or issues with doing that?

@ocombe If you have a quick second, can you comment on why you're running the `$parse(...).assign($scope, null)` bit of code in this unbind? It seems like it's not doing anything, but maybe I'm missing something?

**Comment by ocombe** [comment]
I have no idea, it was too long ago :)

**Comment by scotttrinh** [comment]
@ocombe thanks for weighing in, just wanted to make sure @martinbrylski and I weren't missing anything.

**Comment by scotttrinh** [comment]
@martinbrylski 
I want to push this forward, but it's pretty out of date. Let me know in the next couple of days if you want to update this, or if you're cool with me re-submitting myself with the suggested changes in the issue you opened.

**Pull request closed without merging**
